version: '3'

services:
    app-retention:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: app-retention
        restart: unless-stopped
        volumes:
            - ./:/usr/scr/app
            - app_retention_node_modules:/usr/src/app/node_modules
        ports:
            - 8082:80

volumes:
    app_retention_node_modules:
